#server:
#  port: 8000
spring:
  datasource:
    url: jdbc:mysql://106.15.95.26:3306/zzk?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: zzk
    password: zzk123
    driver-class-name: com.mysql.jdbc.Driver
#mybatis:
#  mapper-locations: classpath:generator/*.xml
logging:
  level:
    com.tjpu.zzk: debug

