#server:
#  port: 8000
spring:
  datasource:
    url: jdbc:mysql://106.15.95.26:3306/zzk?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: zzk
    password: zzk123
    driver-class-name: com.mysql.cj.jdbc.Driver

  freemarker:
    cache: false # 缓存配置 开发阶段应该配置为false 因为经常会改
    suffix: .html # 模版后缀名 默认为ftl
    charset: UTF-8 # 文件编码
    template-loader-path: classpath:/templates/
  security:
    loginType: JSON
    user:
      name: admin
      password: admin
#mybatis:
#  mapper-locations: classpath:generator/*.xml
logging:
  level:
    com.tjpu.zzk: debug

